checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                bitwise: false
            other:
                after_type_cast: false
build: true
filter:
        paths: [PHPCI/*]
tools:
   php_cpd:
        excluded_dirs: [vendor]
    php_pdepend:
        excluded_dirs: [vendor]
    sensiolabs_security_checker: true
    php_changetracking: true
