checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                bitwise: false
            other:
                after_type_cast: false
build:
    environment:
        php:
            version: 5.6
            ini:
                'date.timezone': 'Europe/Andorra'
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=phpunit-coverage-output'
                coverage:
                    file: 'phpunit-coverage-output'
                    format: 'php-clover'
filter:
    paths: [PHPCI/*]
tools:
    php_cpd:
        excluded_dirs: [vendor]
    php_pdepend:
        excluded_dirs: [vendor]
    sensiolabs_security_checker: true
    php_changetracking: true
